# Generated by Django 4.2.17 on 2025-01-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='atmosphere',
            new_name='atmosphere_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='catering',
            new_name='catering_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='facilities',
            new_name='facilities_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='location',
            new_name='location_rating',
        ),
    ]
