# Generated by Django 4.2.17 on 2025-01-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_review_atmosphere_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='atmosphere_rating',
            field=models.CharField(choices=[('A', 'Poor'), ('B', 'Average'), ('C', 'Good'), ('D', 'Outstanding')], default='B', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='catering_rating',
            field=models.CharField(choices=[('A', 'Poor'), ('B', 'Average'), ('C', 'Good'), ('D', 'Outstanding')], default='B', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='facilities_rating',
            field=models.CharField(choices=[('A', 'Poor'), ('B', 'Average'), ('C', 'Good'), ('D', 'Outstanding')], default='B', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='final_score',
            field=models.CharField(choices=[('A', 'Poor'), ('B', 'Average'), ('C', 'Good'), ('D', 'Outstanding')], default='B', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='location_rating',
            field=models.CharField(choices=[('A', 'Poor'), ('B', 'Average'), ('C', 'Good'), ('D', 'Outstanding')], default='B', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.CharField(choices=[('A', 'Poor'), ('B', 'Average'), ('C', 'Good'), ('D', 'Outstanding')], default='B', max_length=10),
        ),
    ]
