# Generated by Django 4.2.17 on 2025-01-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_alter_review_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PremierLeagueTeam',
        ),
    ]
