# Generated by Django 4.2.17 on 2025-01-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_delete_premierleagueteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='team_visited',
            field=models.CharField(choices=[('Arsenal', 'Arsenal'), ('Villa', 'Aston Villa'), ('Bouremouth', 'Bournemouth'), ('Brentford', 'Brentford'), ('Brighton', 'Brighton'), ('Chelsea', 'Chelsea'), ('Palace', 'Crystal Palace'), ('Everton', 'Everton'), ('Fulham', 'Fulham'), ('Ipswich', 'Ipswich'), ('Leicester', 'Leicester City'), ('Man City', 'Manchester City'), ('Man Utd', 'Manchester United'), ('Newcastle', 'Newcastle'), ('Forst', 'Nottingham Forest'), ('SOuthmpton', 'Southampton'), ('Spurs', 'Tottenham Hotspur'), ('West Ham', 'West Ham'), ('Wolves', 'Wolverhampton Wanderers')], default='ARS', max_length=30),
        ),
    ]
