# Generated by Django 4.2.17 on 2025-01-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_alter_review_team_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='my_team',
            field=models.CharField(choices=[('Arsenal', 'Arsenal'), ('Aston Villa', 'Aston Villa'), ('Barnsley', 'Barnsley'), ('Birmingham City', 'Birmingham City'), ('Blackburn Rovers', 'Blackburn Rovers'), ('Blackpool', 'Blackpool'), ('Bolton Wanderers', 'Bolton Wanderers'), ('Bournemouth', 'Bournemouth'), ('Brentford', 'Brentford'), ('Brighton & Hove Albion', 'Brighton & Hove Albion'), ('Bristol City', 'Bristol City'), ('Burnley', 'Burnley'), ('Burton Albion', 'Burton Albion'), ('Cambridge United', 'Cambridge United'), ('Cardiff City', 'Cardiff City'), ('Carlisle United', 'Carlisle United'), ('Charlton Athletic', 'Charlton Athletic'), ('Chelsea', 'Chelsea'), ('Cheltenham Town', 'Cheltenham Town'), ('Coventry City', 'Coventry City'), ('Crystal Palace', 'Crystal Palace'), ('Derby County', 'Derby County'), ('Exeter City', 'Exeter City'), ('Everton', 'Everton'), ('Fleetwood Town', 'Fleetwood Town'), ('Fulham', 'Fulham'), ('Huddersfield Town', 'Huddersfield Town'), ('Hull City', 'Hull City'), ('Ipswich Town', 'Ipswich Town'), ('Leeds United', 'Leeds United'), ('Leicester City', 'Leicester City'), ('Leyton Orient', 'Leyton Orient'), ('Lincoln City', 'Lincoln City'), ('Liverpool', 'Liverpool'), ('Luton Town', 'Luton Town'), ('Manchester City', 'Manchester City'), ('Manchester United', 'Manchester United'), ('Middlesbrough', 'Middlesbrough'), ('Millwall', 'Millwall'), ('Newcastle United', 'Newcastle United'), ('Northampton Town', 'Northampton Town'), ('Norwich City', 'Norwich City'), ('Nottingham Forest', 'Nottingham Forest'), ('Oxford United', 'Oxford United'), ('Peterborough United', 'Peterborough United'), ('Plymouth Argyle', 'Plymouth Argyle'), ('Port Vale', 'Port Vale'), ('Portsmouth', 'Portsmouth'), ('Preston North End', 'Preston North End'), ('Queens Park Rangers', 'Queens Park Rangers'), ('Reading', 'Reading'), ('Rotherham United', 'Rotherham United'), ('Sheffield United', 'Sheffield United'), ('Sheffield Wednesday', 'Sheffield Wednesday'), ('Shrewsbury Town', 'Shrewsbury Town'), ('Southampton', 'Southampton'), ('Stevenage', 'Stevenage'), ('Stoke City', 'Stoke City'), ('Sunderland', 'Sunderland'), ('Swansea City', 'Swansea City'), ('Tottenham Hotspur', 'Tottenham Hotspur'), ('Watford', 'Watford'), ('West Bromwich Albion', 'West Bromwich Albion'), ('West Ham United', 'West Ham United'), ('Wigan Athletic', 'Wigan Athletic'), ('Wolverhampton Wanderers', 'Wolverhampton Wanderers')], default='ARS', max_length=30),
        ),
    ]
